set_property PACKAGE_PIN W8 [get_ports BM_RX]
set_property IOSTANDARD LVCMOS33 [get_ports BM_RX]
set_property PACKAGE_PIN Y9 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN T22 [get_ports LED]
set_property IOSTANDARD LVCMOS33 [get_ports LED]
set_property PACKAGE_PIN R16 [get_ports RST]
set_property IOSTANDARD LVCMOS18 [get_ports RST]
