set_property PACKAGE_PIN Y9 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN R16 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property PACKAGE_PIN F22 [get_ports EN]
set_property IOSTANDARD LVCMOS33 [get_ports EN]
set_property PACKAGE_PIN K15 [get_ports UART_RX_EXT]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RX_EXT]
set_property PACKAGE_PIN J15 [get_ports UART_TX_EXT]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX_EXT]
set_property PACKAGE_PIN W11 [get_ports UART_RX_INT]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RX_INT]
set_property PACKAGE_PIN W12 [get_ports UART_TX_INT]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX_INT]

set_property PACKAGE_PIN U21 [get_ports REC_BLK]
set_property PACKAGE_PIN U22 [get_ports REC_ECU]
set_property PACKAGE_PIN T22 [get_ports REC_THS]
set_property PACKAGE_PIN T21 [get_ports REC_MCU]
set_property IOSTANDARD LVCMOS33 [get_ports REC_BLK]
set_property IOSTANDARD LVCMOS33 [get_ports REC_THS]
set_property IOSTANDARD LVCMOS33 [get_ports REC_MCU]
set_property IOSTANDARD LVCMOS33 [get_ports REC_ECU]


set_property OFFCHIP_TERM NONE [get_ports MCU_GPIO_EXT]
set_property OFFCHIP_TERM NONE [get_ports REC_BLK]
set_property OFFCHIP_TERM NONE [get_ports REC_ECU]
set_property OFFCHIP_TERM NONE [get_ports REC_MCU]
set_property OFFCHIP_TERM NONE [get_ports REC_THS]
set_property OFFCHIP_TERM NONE [get_ports UART_RX_INT]
set_property OFFCHIP_TERM NONE [get_ports UART_TX_EXT]
set_property PACKAGE_PIN V22 [get_ports MCU_GPIO_EXT]
set_property IOSTANDARD LVCMOS33 [get_ports MCU_GPIO_EXT]
set_property PACKAGE_PIN G22 [get_ports MCU_GPIO_INT]
set_property IOSTANDARD LVCMOS33 [get_ports MCU_GPIO_INT]
